add check for nvim, and use single brackets over doubles

diff --git a/install b/install
--- a/install
+++ b/install
@@ -24,10 +24,10 @@ echo -n 'Installing zsh-syntax-highlighting... '
 zsh_git_dir="$cfgdir/zsh/zsh-syntax-highlighting"
 zsh_git_repo='https://github.com/zsh-users/zsh-syntax-highlighting.git'
 
-[[ -d $zsh_git_dir ]] && rm -rf $zsh_git_dir
+[ -d $zsh_git_dir ] && rm -rf $zsh_git_dir
 
 git clone $zsh_git_repo $zsh_git_dir > /dev/null 2>&1
-[[ "$?" -ne 0 ]] && echo -n "failed. "
+[ "$?" -ne 0 ] && echo -n "failed. "
 
 echo "Done"
 echo
@@ -53,7 +53,7 @@ plugurl='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
 
 tmpout=$(mktemp)
 curl -fLo $vimaudir/plug.vim --silent --create-dirs $plugurl
-if [[ "$?" -eq 0 ]]; then
+if [ "$?" -eq 0 ] && [ command -v nvim > /dev/null 2>&1 ]; then
     mkdir -p $nvimaudir
     cp $vimaudir/plug.vim $nvimaudir
 else
